### PR TITLE
fix: send SIGTERM to job when trying to exit

### PR DESCRIPTION
**Pull request by N-R-K**
Fixes: https://github.com/mcchrish/nnn.vim/pull/123#issuecomment-947805683

### CODE REVIEW

**Comment by jarun** [comment]
Yes, it's fixed.

However, I still see:

```
mkfifo: cannot create fifo '/tmp/vHsmzKA/0': File exists
```

**Comment by N-R-K** [comment]
> However, I still see:
> 
> ```
> mkfifo: cannot create fifo '/tmp/vHsmzKA/0': File exists
> ```

Can't reproduce. Can you manually delete that file and see if the issue is reproducible on your end?

**Comment by jarun** [comment]
It's a new file everytime.
But I noticed that I see this error if I just open the explorer (but not any new file using it).
This is thrown by mkfifo(). Are you trying to create a fifo that already exists?

**Comment by N-R-K** [comment]
> This is thrown by `mkfifo`. Are you trying to create a fifo that already exists?

Fifo should be only created at `:NnnExplorer` startup.

https://github.com/mcchrish/nnn.vim/blob/d0f47ba44a4423754c122fd6e90b2dcc4e28f821/autoload/nnn.vim#L392

We're creating this ourselves to avoid the sleep hack. I saw @luukvbaal do it on `nnn.nvim` as well.

**Comment by N-R-K** [comment]
@jarun I can reproduce the issue now after adding a `sleep 2` after `s:build_window`. This means nnn is creating the fifo before us. I'll open the PR with the fix.

**Pull request merged**
