### PR TITLE
fix issue with vim-popup

### LINKED ISSUE #46: Support vim popup
As the title says. Neovim and soon Vim will support floating window. Would be nice that the plugin can support it.

### PR DESCRIPTION
**Pull request by mcchrish**
Closes #46

### CODE REVIEW

**Comment by jarun** [comment]
Shall we have simple examples in RREADME for both neovim and vim?

**Comment by mcchrish** [comment]
Works the same with neovim and vim now, but added notes what version of vim is needed in README.

**Comment by jarun** [comment]
Thank you! Ready info and examples always help for people like me. Always short of time. :(

BTW, I hope you and your family are safe at this time of crisis.

**Comment by mcchrish** [comment]
Thanks! Hope your doing fine too.

**Comment by jarun** [comment]
Yes, we are doing OK so far. Completely quarantined.

**Pull request merged**
